#!/usr/bin/env python3
"""Turn results/summary.json into LaTeX macros (numbers.tex) and the CSL table
(table_csl.tex) so every number in the manuscript is generated, not typed."""

import json
import os
import sys

import numpy as np

root = os.path.dirname(os.path.abspath(__file__))
summary = json.load(open(sys.argv[1] if len(sys.argv) > 1 else
                         os.path.join(root, "..", "results", "summary.json")))
M = {}


def f2(x):
    return f"{x:.2f}"


def pct(x):
    return f"{100 * x:.1f}"


# ---- delay realisation --------------------------------------------------
d = summary["delay"]
below = [r["rel_l2_error"] for r in d if r["S"] < r["k"]]
at = [r["rel_l2_error"] for r in d if r["S"] >= r["k"]]
M["delayErrBelow"] = f2(np.median(below))
M["delayErrAbove"] = f2(np.median(at))
M["delayErrMinBelow"] = f2(np.min(below))
over = []
for k in sorted({r["k"] for r in d}):
    rr = sorted((r for r in d if r["k"] == k), key=lambda r: r["S"])
    s10 = next((r["S"] for r in rr if r["rel_l2_error"] <= 0.1), None)
    if s10:
        over.append(s10 / k)
M["delayOverhead"] = f"{np.median(over):.1f}" if over else "--"

# ---- phase diagram -------------------------------------------------------
p = summary["phase"]
for tag, model in (("LTI", "lti"), ("Sel", "selective")):
    rr = [r for r in p if r["model"] == model]
    M[f"phaseAucBelow{tag}"] = f2(np.mean([r["auroc"] for r in rr if r["S"] < r["k"]]))
    M[f"phaseAucAbove{tag}"] = f2(np.mean([r["auroc"] for r in rr if r["S"] >= 4 * r["k"]]))
    th = [t for t in summary["phase_thresholds"] if t["model"] == model]
    ratios = [t["ratio"] for t in th if t["ratio"] is not None]
    M[f"phaseRatio{tag}"] = f"{np.median(ratios):.1f}" if ratios else "--"
    M[f"phaseReached{tag}"] = str(len(ratios))
    M[f"phaseNk{tag}"] = str(len(th))
    M[f"phaseMaxK{tag}"] = str(max([t["k"] for t in th if t["ratio"] is not None], default=0))
diff = []
for r in p:
    if r["model"] == "lti":
        q = [x for x in p if x["model"] == "selective" and x["S"] == r["S"] and x["k"] == r["k"]
             and x["seed"] == r["seed"]]
        if q:
            diff.append(q[0]["auroc"] - r["auroc"])
M["phaseSelMinusLTI"] = f"{np.mean(diff):+.3f}"
M["phaseSelMinusLTIabs"] = f"{np.mean(np.abs(diff)):.3f}"

# ---- CSL -----------------------------------------------------------------
c = summary["csl"]
Ss = sorted({r["S"] for r in c})
acc = {}
for model in ("lti", "selective", "oracle"):
    for S in Ss:
        v = [r["acc"] for r in c if r["model"] == model and r["S"] == S]
        if v:
            acc[(model, S)] = (np.mean(v), np.std(v))
Smax = max(Ss)
for tag, model in (("LTI", "lti"), ("Sel", "selective"), ("Or", "oracle")):
    best = max((acc[(model, S)] + (S,) for S in Ss if (model, S) in acc), key=lambda t: t[0])
    M[f"csl{tag}Best"], M[f"csl{tag}BestStd"], M[f"csl{tag}BestS"] = pct(best[0]), pct(best[1]), str(best[2])
    M[f"csl{tag}AtMax"] = pct(acc[(model, Smax)][0])
M["cslSmax"] = str(Smax)
M["cslOrOnsetS"] = str(next((S for S in Ss if acc[("oracle", S)][0] >= 0.95), "--"))
ons = summary["csl_onsets"]
for tag, model in (("LTI", "lti"), ("Sel", "selective"), ("Or", "oracle")):
    rr = [o for o in ons if o["model"] == model]
    M[f"cslClasses{tag}"] = str(sum(o["onset_S"] is not None for o in rr))
    M[f"cslExact{tag}"] = str(sum(o["onset_S"] == o["predicted_S"] for o in rr))
    grid_up = lambda w: min((S for S in Ss if S >= w), default=None)
    M[f"cslGrid{tag}"] = str(sum(o["onset_S"] == grid_up(o["predicted_S"]) for o in rr))
    M[f"cslBelow{tag}"] = str(sum(o["onset_S"] is not None and o["onset_S"] < o["predicted_S"]
                                  for o in rr))
    x = np.array([o["predicted_S"] for o in rr if o["onset_S"]], float)
    y = np.array([o["onset_S"] for o in rr if o["onset_S"]], float)
    M[f"cslSlope{tag}"] = f"{(x * y).sum() / (x * x).sum():.1f}" if len(x) else "--"

W = summary["csl_horizon_W"]
M["cslWmin"], M["cslWmax"] = str(min(W.values())), str(max(W.values()))

with open(os.path.join(root, "numbers.tex"), "w") as fh:
    fh.write("% auto-generated by make_numbers.py -- do not edit\n")
    for k, v in M.items():
        fh.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")

# ---- Table: horizons and onsets -------------------------------------------
by = {(o["model"], o["skip"]): o["onset_S"] for o in ons}
fmt = lambda v: "--" if v is None else str(v)
skips = sorted({o["skip"] for o in ons})
rows = [
    r"$s$ & " + " & ".join(map(str, skips)) + r" \\ \midrule",
    r"$W^*(s)$ & " + " & ".join(str(W[str(s)]) for s in skips) + r" \\",
    r"Oracle & " + " & ".join(fmt(by[("oracle", s)]) for s in skips) + r" \\",
    r"LTI & " + " & ".join(fmt(by[("lti", s)]) for s in skips) + r" \\",
    r"Selective & " + " & ".join(fmt(by[("selective", s)]) for s in skips) + r" \\",
]
with open(os.path.join(root, "table_csl.tex"), "w") as fh:
    fh.write("% auto-generated by make_numbers.py -- do not edit\n"
             "\\begin{tabular}{lcccccccccc}\n\\toprule\n" + "\n".join(rows)
             + "\n\\bottomrule\n\\end{tabular}\n")

for k, v in M.items():
    print(f"{k:24s} {v}")
